### ISSUE TITLE
code

### ISSUE THREAD

**Issue by skskgrowl** [afford-motion/afford-motion#1]
Thank you for your excellent work, when will you release the training code?

**Comment by Silverster98** [comment]
> Thank you for your excellent work, when will you release the training code?

Thanks for your attention. I will release the code in the next few weeks.

**Comment by Silverster98** [comment]
Sorry for the late response. I have released the code and data now. Please check the repository. If you have any questions, feel free to let me know by creating a new issue. I will close this issue.
