### ISSUE TITLE
How to visualize the motion in scene on the HumanML3D benchmark

### ISSUE THREAD

**Issue by ZhiyangLiang** [afford-motion/afford-motion#14]
Hi, thanks for the great work and amazing code!
I have a small question: How to visualize the motion in scene on the HumanML3D benchmark? I have tried the visualize_h3d.py and found that it can only visualize joints. Looking forward to your reply~

**Comment by Silverster98** [comment]
Hi, I follow the HumanML3D to convert the skeleton into SMPL mesh; please refer to https://github.com/EricGuo5513/HumanML3D/issues/1.
For all results in the paper, I first save the results as `.obj`/`.ply` files and then import them into Blender for manual rendering.

**Comment by ZhiyangLiang** [comment]
Thanks for your reply!
Maybe I didn't phrase it very clear. I know how to convert the skeleton into SMPL mesh and I want to visualize the motion together with the scene (interaction with the scene) on the HumanML3D benchmark, just like on the HUMANISE betchmark:
![image](https://github.com/user-attachments/assets/6c6ec99c-9ee0-4eab-9c7e-8529afa9b72a)
But the visualization on the HumanML3D benchmark does not include the scene:
![image](https://github.com/user-attachments/assets/1da36501-eac2-40fd-a548-e95e67191b20)
Looking forward to your reply~

**Comment by Silverster98** [comment]
I see. But, the HumanML3D benchmark doesn't include the 3D scene. In the experiment on the HumanML3D benchmark, our work just augments the HumanML3D motion sequences with a ground without other objects, so we didn't visualize it.

**Comment by ZhiyangLiang** [comment]
Okay, thanks for your reply again!
