### ISSUE TITLE
missing "floor_colors.json" file

### ISSUE THREAD

**Issue by Xuehao-Gao** [afford-motion/afford-motion#15]
Hi,
     When I prepare my own dataset following your [instruction,](https://github.com/afford-motion/afford-motion/blob/main/prepare/README.md) I meet the error that "No such file or directory: './prepare/floor_colors.json'". I think this file may be missing in this repository.
Thx

**Comment by Haodong-Yan** [comment]
How to address this issue?

**Comment by Silverster98** [comment]
It is not used; ignore it.
