### ISSUE TITLE
can't download dataset

### ISSUE THREAD

**Issue by nancy-ux** [afford-motion/afford-motion#5]
hi! Very much appreciate your work. 
However, I can't download the dataset through one-drive. I have tried using the web browser and other software to help download, but it didn't work :( . 
Can u provide other ways to download the data, such as the baidu disc?
Thank you very much!!!!

**Comment by Silverster98** [comment]
Hi, I am uploading the data to the Baidu disk. You can check it later today. The share link is here https://pan.baidu.com/s/1U48TK1FdNU4jZuNShJPGdA?pwd=gg65.

**Comment by nancy-ux** [comment]
> Hi, I am uploading the data to the Baidu disk. You can check it later today. The share link is here https://pan.baidu.com/s/1K9t_atenvjuntcYTp4a_8A?pwd=ciyy.

thank you very much!
