### ISSUE TITLE
 Error while finding module specification for 'eval.eval_h3d_offline' (ModuleNotFoundError: No module named 'eval')

### ISSUE THREAD

**Issue by keke19961117** [afford-motion/afford-motion#6]
Can not evaluate,there is on eval found ,how to solve that?

**Comment by Silverster98** [comment]
Hi, did you follow the steps in [readme](https://github.com/afford-motion/afford-motion/tree/main?tab=readme-ov-file#3-calculate-metrics) for computing metrics using MDM code? The eval folder is located in the [MDM](https://github.com/GuyTevet/motion-diffusion-model) repository.

**Comment by keke19961117** [comment]
Yes, I followed. That maybe some other errors occured , the question just disappeared, bust raised the IndexError: tuple index out of range with /motion-diffusion-model/data_loaders/humanml/data/dataset.py", line 307, data = self.data_dict[self.name_list[idx]], have you met this problem and how to fix it?

**Comment by Silverster98** [comment]
I didn't encounter such a problem. From this error, I noticed that you have changed the MDM code (Line 307 is not such code). I don't know if your change can result in such an error. Besides, did you follow MDM to prepare the data and environment? During the evaluation, the MDM code will load the data to compute a metric for the real set, so you should also prepare the data. (You can use a soft link to link our preprocessed data into the specified location in the MDM repository)

**Comment by Silverster98** [comment]
I don't think this error is caused by the torch version. But you can try running the MDM evaluation code first; if you can run it successfully, try to run ours. It's better to first identify whether the problem is in MDM or our code.

**Comment by keke19961117** [comment]
The error is the same to run MDM's evaluate，I'll try the environment provided by MDM.



---Original---
From: "Zan ***@***.***&gt;
Date: Mon, Jul 15, 2024 17:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [afford-motion/afford-motion]  Error while finding modulespecification for 'eval.eval_h3d_offline' (ModuleNotFoundError: No modulenamed 'eval') (Issue #6)




 
I don't think this error is caused by the torch version. But you can try running the MDM evaluation code first; if you can run it successfully, try to run ours. It's better to first identify whether the problem is in MDM or our code.

**Comment by keke19961117** [comment]
Hi, I would like to know how to generate 3D animations based on your code repository.Like the page showed at github and in your paper. Can you please provide me with some guidance?



---Original---
From: "Zan ***@***.***&gt;
Date: Mon, Jul 15, 2024 17:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [afford-motion/afford-motion]  Error while finding modulespecification for 'eval.eval_h3d_offline' (ModuleNotFoundError: No modulenamed 'eval') (Issue #6)




 
I don't think this error is caused by the torch version. But you can try running the MDM evaluation code first; if you can run it successfully, try to run ours. It's better to first identify whether the problem is in MDM or our code.

**Comment by Silverster98** [comment]
I first export the generated results into meshes and then use Blender to render the video. To export the mesh, you can follow [this issue](https://github.com/afford-motion/afford-motion/issues/7).
