### ISSUE TITLE
demo for qualitative results

### ISSUE THREAD

**Issue by yw0208** [afford-motion/afford-motion#7]
Great work!
Do you plan to release codes for visualizing generated motions in scenes?
It would be very helpful.

**Comment by Silverster98** [comment]
Hi, I upload a [script](https://github.com/afford-motion/afford-motion/blob/main/visualize.py) for visualization. Please check it. A simple way to use it:
```bash
python visualize.py --file ${PKL} --render_joint
```

- `--file` indicates the result for rendering. ${PKL} is the saved result in your evaluation folder, such `./outputs/CMDM-Enc-ALL/eval/test-0101-00000/joints/00000.pkl`
- `--render_joint` indicates rendering SMPL joints instead of mesh

Please read the code for other options.

**Comment by yw0208** [comment]
Thank you!

**Comment by RuiqingTang** [comment]
@Silverster98 
Hi,
I executed the following two commands:
```
 bash scripts/t2m_contact/test.sh ./outputs/CDM-Perceiver-H3D/ wo_mm 2023
 bash scripts/t2m_contact_motion/test.sh outputs/CMDM-Enc-H3D-mixtrain0.5/ outputs/CDM-Perceiver-H3D/eval/test-0413-205430 wo_mm 2023
```
But I only found the pkl files in this directory `./outputs/CMDM-Enc-H3D-mixtrain0.5/eval/test-0724-160958/humanml`, not the directory `./outputs/CMDM-Enc-ALL/eval/test-0101-00000/joints/00000.pkl` you mentioned.
When I tried to visualize the results, I got the following error:
```
{'name': '000019', 'text': 'person jogs around to the left and right', 'tokens': ['person/NOUN', 'jog/VERB', 'around/ADV', 'to/ADP', 'the/DET', 'left/NOUN', 'and/CCONJ', 'right/ADJ'], 'motion': array([[-0.06990062, -0.00862925,  0.00903702, ...,  1.0038702 ,
         1.0151486 ,  1.0112567 ],
       [-0.00418399, -0.01324492,  0.0117446 , ...,  1.0018142 ,
         1.0092654 ,  1.0076082 ],
       [-0.00383292, -0.01627299,  0.01388093, ...,  1.0013393 ,
         1.0064111 ,  1.0092889 ],
       ...,
       [-0.01218314,  0.01191701,  0.01579641, ...,  1.0083191 ,
         1.0126897 ,  1.0093919 ],
       [-0.00932829,  0.00845526,  0.00773508, ...,  1.0063035 ,
         1.0096298 ,  1.0092592 ],
       [-0.00834997,  0.01137932,  0.00447602, ...,  1.0062536 ,
         1.0091835 ,  1.0116569 ]], dtype=float32), 'm_len': 148}
Traceback (most recent call last):
  File "visualize.py", line 160, in <module>
    body_meshes, scene_mesh = rendering(f, os.path.join(prefix, 'video', f'{basename}'), args.render_joint)
  File "visualize.py", line 85, in rendering
    joints = data['joints']
KeyError: 'joints'
```

**Comment by Silverster98** [comment]
> @Silverster98 Hi, I executed the following two commands:
> 
> ```
>  bash scripts/t2m_contact/test.sh ./outputs/CDM-Perceiver-H3D/ wo_mm 2023
>  bash scripts/t2m_contact_motion/test.sh outputs/CMDM-Enc-H3D-mixtrain0.5/ outputs/CDM-Perceiver-H3D/eval/test-0413-205430 wo_mm 2023
> ```
> 
> But I only found the pkl files in this directory `./outputs/CMDM-Enc-H3D-mixtrain0.5/eval/test-0724-160958/humanml`, not the directory `./outputs/CMDM-Enc-ALL/eval/test-0101-00000/joints/00000.pkl` you mentioned. When I tried to visualize the results, I got the following error:
> 
> ```
> {'name': '000019', 'text': 'person jogs around to the left and right', 'tokens': ['person/NOUN', 'jog/VERB', 'around/ADV', 'to/ADP', 'the/DET', 'left/NOUN', 'and/CCONJ', 'right/ADJ'], 'motion': array([[-0.06990062, -0.00862925,  0.00903702, ...,  1.0038702 ,
>          1.0151486 ,  1.0112567 ],
>        [-0.00418399, -0.01324492,  0.0117446 , ...,  1.0018142 ,
>          1.0092654 ,  1.0076082 ],
>        [-0.00383292, -0.01627299,  0.01388093, ...,  1.0013393 ,
>          1.0064111 ,  1.0092889 ],
>        ...,
>        [-0.01218314,  0.01191701,  0.01579641, ...,  1.0083191 ,
>          1.0126897 ,  1.0093919 ],
>        [-0.00932829,  0.00845526,  0.00773508, ...,  1.0063035 ,
>          1.0096298 ,  1.0092592 ],
>        [-0.00834997,  0.01137932,  0.00447602, ...,  1.0062536 ,
>          1.0091835 ,  1.0116569 ]], dtype=float32), 'm_len': 148}
> Traceback (most recent call last):
>   File "visualize.py", line 160, in <module>
>     body_meshes, scene_mesh = rendering(f, os.path.join(prefix, 'video', f'{basename}'), args.render_joint)
>   File "visualize.py", line 85, in rendering
>     joints = data['joints']
> KeyError: 'joints'
> ```

Hi, sorry for this late reply. As this issue was closed, I didn't notice your comments.

I visualize the result on the HumanML3D benchmark using another visualization script, `visualize_h3d.py`, which I have uploaded to this repo. I hope this can solve your issue.
