### ISSUE TITLE
Dataset preparation 

### ISSUE THREAD

**Issue by Yasaman-Haghighi** [afford-motion/afford-motion#8]
Hello,

Thank you for the interesting work and sharing the code and the data! Is it possible to provide a quick description of the preprocessing steps of each dataset?

Thank you in advance for your consideration.

Best regards,
Yasaman

**Comment by Silverster98** [comment]
Hi! Apologies for the late reply—I needed some time to prepare the code and README for dataset preparation. The repository has now been updated. You can find more details about the data preparation process at https://github.com/afford-motion/afford-motion/blob/main/prepare/README.md. Please note that the process is somewhat complex, and the cleaned code hasn't been thoroughly tested yet, but it should still serve as a helpful reference.
